---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This code will simulate a GxE effect on Normal outcome and test & estimate the variance effect

```{r setup}
library("varGWASR")
set.seed(1234)

n_obs <- 1000
n_sim <- 200
maf <- 0.4

# main effect size of x on y detectable ~ 95% power
delta <- 0.17

# simulation
for (phi in seq(0, 6, .5)){
  # size of interaction relative to main effect (Brookes et al)
  theta <- delta * phi
  
  results <- data.frame()
  for (i in 1:n_sim) {
      # simulate GxE interaction effect
      x <- rbinom(n_obs, 2, maf)
      u <- rnorm(n_obs)
      y <- x * delta + x*u * theta + rnorm(n_obs)

      # test/estimate variance effect
      fit <- varGWASR::model(data.frame(x, y), "x", "y")

      # add true variance difference
      fit$v1 <- var(y[x==1]) - var(y[x==0])
      fit$v2 <- var(y[x==2]) - var(y[x==0])
    
      # store result
      fit$phi <- phi
      results <- rbind(results, fit)
  }
}
```
